codecov:
  notify:
    after_n_builds: 2

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

comment:
  require_changes: true
  after_n_builds: 2

github_checks:
  annotations: false

flags:
  cli:
    paths:
      - packages/tols/
    carryforward: false
  web:
    paths:
      - apps/web/
    carryforward: false
