// Tool registry aggregator: importing this module registers every CLI tool.
// New tools: create src/tools/<name>.js (default export = tool def), then add
// the register call here.
import { register } from '../registry.js';
import base64 from './base64.js';
import url from './url.js';
import json from './json.js';
import yaml from './yaml.js';
import diff from './diff.js';
import timestamp from './timestamp.js';
import cron from './cron.js';
import uuid from './uuid.js';
import hash from './hash.js';
import jwt from './jwt.js';
import gzip from './gzip.js';
import base from './base.js';
import password from './password.js';
import unicode from './unicode.js';
import timezone from './timezone.js';
import color from './color.js';
import cssfilter from './cssfilter.js';
import datauri from './datauri.js';
import placeholder from './placeholder.js';
import lorem from './lorem.js';
import jsonp from './jsonp.js';
import css from './css.js';
import html from './html.js';
import xml from './xml.js';
import sql from './sql.js';
import markdown from './markdown.js';
import regex from './regex.js';
import qrcode from './qrcode.js';
import barcode from './barcode.js';

register(base64);
register(url);
register(json);
register(yaml);
register(diff);
register(timestamp);
register(cron);
register(uuid);
register(hash);
register(jwt);
register(gzip);
register(base);
register(password);
register(unicode);
register(timezone);
register(color);
register(cssfilter);
register(datauri);
register(placeholder);
register(lorem);
register(jsonp);
register(css);
register(html);
register(xml);
register(sql);
register(markdown);
register(regex);
register(qrcode);
register(barcode);
