<script>
  import QrcodeTool from '$lib/tools/QrcodeTool.svelte'

  const pageTitle = 'QR Code Generator - DevUtils | Free QR Code Creator'
  const pageDescription = 'Free online QR code generator tool for everyone. Create QR codes from text and URLs instantly with size controls, error correction, and download options.'
  const canonicalUrl = 'https://arasovic.github.io/dev-utilities/qrcode'
  const ogImage = 'https://arasovic.github.io/dev-utilities/og-image.svg'
</script>

<svelte:head>
  <title>{pageTitle}</title>
  <meta name="description" content={pageDescription} />
  <meta name="keywords" content="QR code generator, QR code creator, free QR code, online QR code" />
  <link rel="canonical" href={canonicalUrl} />

  <meta property="og:title" content={pageTitle} />
  <meta property="og:description" content={pageDescription} />
  <meta property="og:type" content="website" />
  <meta property="og:url" content={canonicalUrl} />
  <meta property="og:image" content={ogImage} />
  <meta property="og:site_name" content="DevUtils" />

  <meta name="twitter:card" content="summary_large_image" />
  <meta name="twitter:title" content={pageTitle} />
  <meta name="twitter:description" content={pageDescription} />
  <meta name="twitter:image" content={ogImage} />

  {@html `<script type="application/ld+json">${JSON.stringify({
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    "name": "QR Code Generator",
    "applicationCategory": "DeveloperApplication",
    "operatingSystem": "Any",
    "offers": { "@type": "Offer", "price": "0", "priceCurrency": "USD" },
    "description": pageDescription,
    "featureList": [
      "Multiple formats",
      "Error correction",
      "Customizable size",
      "PNG and SVG output",
      "Real-time generation",
      "High quality"
    ],
    "url": canonicalUrl,
    "provider": { "@type": "Organization", "name": "DevUtils", "url": "https://arasovic.github.io/dev-utilities" }
  })}</script>`}
</svelte:head>

<main id="main-content">
  <article>
    <QrcodeTool />

    <div class="seo-section">
    <section class="seo-content" aria-labelledby="what-is">
      <h2 id="what-is">What is QR Code Generator?</h2>
      <p>
        QR Code Generator creates scannable QR codes from text, URLs, or other data. QR codes
        (Quick Response codes) are two-dimensional barcodes that can be scanned by smartphones
        and other devices to quickly access information. They're widely used for sharing URLs,
        contact information, WiFi credentials, and more.
      </p>
    </section>

    <section class="seo-content" aria-labelledby="how-to-use">
      <h2 id="how-to-use">How to Use QR Code Generator</h2>
      <ol>
        <li><strong>Enter data</strong> - Type the text, URL, or information to encode</li>
        <li><strong>Customize size</strong> - Choose the QR code dimensions</li>
        <li><strong>Set error correction</strong> - Select error correction level</li>
        <li><strong>Generate and download</strong> - Create and save your QR code as PNG or SVG</li>
      </ol>
    </section>

    <section class="seo-content" aria-labelledby="features">
      <h2 id="features">QR Code Generator Features</h2>
      <ul>
        <li><strong>Multiple formats</strong> - Generate QR codes for URLs, text, email, phone, WiFi, and more</li>
        <li><strong>Error correction</strong> - Four levels: Low, Medium, Quartile, High</li>
        <li><strong>Customizable size</strong> - Adjust QR code dimensions</li>
        <li><strong>PNG and SVG output</strong> - Download in your preferred format</li>
        <li><strong>Real-time generation</strong> - See QR code update as you type</li>
        <li><strong>High quality</strong> - Print-ready resolution</li>
      </ul>
    </section>

    <section class="seo-content" aria-labelledby="faq">
      <h2 id="faq">Frequently Asked Questions</h2>

      <h3>What is error correction in QR codes?</h3>
      <p>
        Error correction allows a QR code to be read even if part of it is damaged or obscured.
        Four levels are available: L (Low) recovers ~7%, M (Medium) ~15%, Q (Quartile) ~25%, and
        H (High) ~30% of the code. Higher levels create larger QR codes but are more resilient.
      </p>

      <h3>What is the maximum data capacity of a QR code?</h3>
      <p>
        QR codes can store up to 7,089 numeric characters, 4,296 alphanumeric characters, or 2,953
        bytes of binary data. However, larger data amounts create denser codes that are harder to
        scan. For best results, keep URLs short and data concise.
      </p>

      <h3>Can I use these QR codes commercially?</h3>
      <p>
        Yes, the QR codes generated by this tool are free to use for both personal and commercial
        purposes. They contain no watermarks or restrictions. You can use them on products,
        marketing materials, business cards, and more.
      </p>
    </section>
    </div>
  </article>
</main>

<style>
  .seo-section {
    margin-top: var(--space-8);
    padding-top: var(--space-8);
    border-top: 1px solid var(--border-subtle);
  }

  .seo-content {
    width: 100%;
    margin-top: var(--space-6);
    padding: var(--space-6);
    background: var(--bg-surface);
    border: 1px solid var(--border-subtle);
    border-radius: var(--radius-lg);
  }

  .seo-content:first-child {
    margin-top: 0;
  }

  .seo-content h2 {
    font-size: var(--text-xl);
    font-weight: var(--font-semibold);
    color: var(--text-primary);
    margin-bottom: var(--space-4);
    padding-bottom: var(--space-2);
    border-bottom: 1px solid var(--border-subtle);
  }

  .seo-content h3 {
    font-size: var(--text-lg);
    font-weight: var(--font-semibold);
    color: var(--text-primary);
    margin-top: var(--space-5);
    margin-bottom: var(--space-2);
  }

  .seo-content p {
    color: var(--text-secondary);
    line-height: var(--leading-relaxed);
    margin-bottom: var(--space-3);
  }

  .seo-content ul,
  .seo-content ol {
    color: var(--text-secondary);
    line-height: var(--leading-relaxed);
    margin-left: var(--space-4);
    margin-bottom: var(--space-3);
  }

  .seo-content li {
    margin-bottom: var(--space-2);
  }

  .seo-content strong {
    color: var(--text-primary);
    font-weight: var(--font-medium);
  }

  @media (max-width: 768px) {
    .seo-section {
      margin-top: var(--space-6);
      padding-top: var(--space-6);
    }

    .seo-content {
      padding: var(--space-4);
      margin-top: var(--space-4);
    }
  }
</style>
